@startuml
title Diagrama de Sequência - Listagem de Hábitos

actor Client

participant "HabitController" as Controller <<Controller>>
participant "HabitService" as Service <<Service>>
participant "HabitMapper" as Mapper <<Control>>
participant "HabitRepository" as Repository <<Repository>>
database "PostgreSQL DB" as DB <<Database>>

Client -> Controller : GET /habits
Controller -> Service : findAll()

Service -> Repository : findAll()
Repository -> DB : SELECT * FROM habits
DB --> Repository : List<Habit>
Repository --> Service : List<Habit>

Service -> Mapper : toDTO(Habit) [loop]
Mapper --> Service : HabitDTO [loop]

Service --> Controller : List<HabitDTO>
Controller --> Client : 200 OK\nBody: List<HabitDTO>
@enduml